// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuujvmuprjcvieufyxiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1dWp2bXVwcmpjdmlldWZ5eGl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzY1ODUsImV4cCI6MjA2NjM1MjU4NX0.6ea3JbxG8bz-12XOxWgrhs9Q8BpJ0XsaiSVJXNyrld4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);